import type { Category, Product, Order } from "./types"

export const categories: Category[] = [
  { id: "laptops", name: "Ноутбуки", icon: "Laptop" },
  { id: "smartphones", name: "Смартфоны", icon: "Smartphone" },
  { id: "audio", name: "Аудио", icon: "Headphones" },
  { id: "gaming", name: "Игры", icon: "Gamepad2" },
  { id: "tablets", name: "Планшеты", icon: "Tablet" },
  { id: "home", name: "Для дома", icon: "House" },
  { id: "photo", name: "Фото", icon: "Camera" },
  { id: "wearables", name: "Гаджеты", icon: "Watch" },
]

export const products: Product[] = [
  {
    id: "macbook-air-m3",
    name: "Ноутбук Aurora Air 13 M3 256GB",
    brand: "Aurora",
    category: "laptops",
    price: 389990,
    oldPrice: 449990,
    rating: 4.9,
    reviews: 1284,
    image: "/products/laptop.png",
    images: ["/products/laptop.png", "/products/laptop.png", "/products/laptop.png"],
    badge: "hit",
    inStock: true,
    description:
      "Ультратонкий ноутбук с чипом M3, безвентиляторным дизайном и временем работы до 18 часов. Идеален для работы, учёбы и творчества.",
    specs: [
      { label: "Процессор", value: "Aurora M3, 8 ядер" },
      { label: "Оперативная память", value: "16 ГБ" },
      { label: "Накопитель", value: "256 ГБ SSD" },
      { label: "Экран", value: "13.6\" Liquid Retina" },
      { label: "Вес", value: "1.24 кг" },
      { label: "Автономность", value: "до 18 часов" },
    ],
  },
  {
    id: "phone-pro-max",
    name: "Смартфон Nova Pro Max 256GB",
    brand: "Nova",
    category: "smartphones",
    price: 549990,
    oldPrice: 599990,
    rating: 4.8,
    reviews: 3420,
    image: "/products/smartphone.png",
    images: ["/products/smartphone.png", "/products/smartphone.png"],
    badge: "hit",
    inStock: true,
    description:
      "Флагманский смартфон с титановым корпусом, тройной камерой 48 Мп и самым мощным мобильным процессором. Снимайте как профессионал.",
    specs: [
      { label: "Экран", value: "6.7\" OLED 120 Гц" },
      { label: "Процессор", value: "Nova A18 Pro" },
      { label: "Камера", value: "48 + 12 + 12 Мп" },
      { label: "Память", value: "256 ГБ" },
      { label: "Аккумулятор", value: "4685 мАч" },
      { label: "Защита", value: "IP68" },
    ],
  },
  {
    id: "headphones-max",
    name: "Наушники SoundWave Max ANC",
    brand: "SoundWave",
    category: "audio",
    price: 179990,
    rating: 4.7,
    reviews: 892,
    image: "/products/headphones.png",
    images: ["/products/headphones.png", "/products/headphones.png"],
    badge: "new",
    inStock: true,
    description:
      "Беспроводные наушники с активным шумоподавлением, пространственным звуком и автономностью до 40 часов.",
    specs: [
      { label: "Тип", value: "Накладные, закрытые" },
      { label: "Шумоподавление", value: "Активное (ANC)" },
      { label: "Автономность", value: "до 40 часов" },
      { label: "Подключение", value: "Bluetooth 5.3" },
      { label: "Вес", value: "385 г" },
    ],
  },
  {
    id: "gaming-pc-rtx",
    name: "Игровой ПК Titan RTX 4070 32GB",
    brand: "Titan",
    category: "gaming",
    price: 899990,
    oldPrice: 999990,
    rating: 4.9,
    reviews: 542,
    image: "/products/gaming-pc.png",
    images: ["/products/gaming-pc.png", "/products/gaming-pc.png"],
    badge: "sale",
    inStock: true,
    description:
      "Мощный игровой компьютер для современных игр в 2K и 4K. Видеокарта RTX 4070, 32 ГБ памяти и быстрый SSD.",
    specs: [
      { label: "Процессор", value: "8 ядер, 16 потоков" },
      { label: "Видеокарта", value: "RTX 4070 12 ГБ" },
      { label: "Память", value: "32 ГБ DDR5" },
      { label: "Накопитель", value: "1 ТБ NVMe SSD" },
      { label: "Охлаждение", value: "Жидкостное" },
    ],
  },
  {
    id: "smartwatch-ultra",
    name: "Часы Pulse Watch Ultra 49mm",
    brand: "Pulse",
    category: "wearables",
    price: 299990,
    rating: 4.6,
    reviews: 1120,
    image: "/products/smartwatch.png",
    images: ["/products/smartwatch.png"],
    inStock: true,
    description:
      "Защищённые смарт-часы с титановым корпусом, GPS, мониторингом здоровья и автономностью до 36 часов.",
    specs: [
      { label: "Корпус", value: "49 мм, титан" },
      { label: "Экран", value: "AMOLED Always-On" },
      { label: "Автономность", value: "до 36 часов" },
      { label: "Защита", value: "10 ATM, MIL-STD" },
      { label: "Датчики", value: "ЭКГ, SpO2, GPS" },
    ],
  },
  {
    id: "tablet-pro",
    name: "Планшет Slate Pro 11 128GB",
    brand: "Slate",
    category: "tablets",
    price: 329990,
    oldPrice: 369990,
    rating: 4.7,
    reviews: 678,
    image: "/products/tablet.png",
    images: ["/products/tablet.png"],
    badge: "sale",
    inStock: true,
    description:
      "Универсальный планшет с поддержкой стилуса, ярким экраном и производительностью настольного уровня.",
    specs: [
      { label: "Экран", value: "11\" Liquid Retina 120 Гц" },
      { label: "Процессор", value: "Slate M2" },
      { label: "Память", value: "128 ГБ" },
      { label: "Камера", value: "12 Мп" },
      { label: "Стилус", value: "Поддержка Slate Pencil" },
    ],
  },
  {
    id: "console-x",
    name: "Игровая консоль PlayBox X 1TB",
    brand: "PlayBox",
    category: "gaming",
    price: 269990,
    rating: 4.8,
    reviews: 2310,
    image: "/products/console.png",
    images: ["/products/console.png"],
    badge: "hit",
    inStock: true,
    description:
      "Игровая консоль нового поколения с поддержкой 4K 120 fps, быстрым SSD и обширной библиотекой игр.",
    specs: [
      { label: "Накопитель", value: "1 ТБ SSD" },
      { label: "Разрешение", value: "до 4K 120 fps" },
      { label: "В комплекте", value: "1 геймпад" },
      { label: "Поддержка", value: "Ray Tracing" },
    ],
  },
  {
    id: "robot-vacuum",
    name: "Робот-пылесос CleanBot Z10",
    brand: "CleanBot",
    category: "home",
    price: 159990,
    oldPrice: 199990,
    rating: 4.5,
    reviews: 445,
    image: "/products/vacuum.png",
    images: ["/products/vacuum.png"],
    badge: "sale",
    inStock: true,
    description:
      "Умный робот-пылесос с лазерной навигацией, влажной уборкой и станцией самоочистки.",
    specs: [
      { label: "Навигация", value: "Лазерный LiDAR" },
      { label: "Мощность", value: "5000 Па" },
      { label: "Уборка", value: "Сухая + влажная" },
      { label: "Автономность", value: "до 180 мин" },
      { label: "Управление", value: "Приложение, голос" },
    ],
  },
  {
    id: "keyboard-mech",
    name: "Клавиатура Click TKL RGB",
    brand: "Click",
    category: "gaming",
    price: 49990,
    rating: 4.6,
    reviews: 312,
    image: "/products/keyboard.png",
    images: ["/products/keyboard.png"],
    badge: "new",
    inStock: true,
    description:
      "Механическая игровая клавиатура с горячей заменой переключателей и настраиваемой подсветкой.",
    specs: [
      { label: "Форм-фактор", value: "TKL (87 клавиш)" },
      { label: "Переключатели", value: "Hot-swap, линейные" },
      { label: "Подсветка", value: "RGB по клавишам" },
      { label: "Подключение", value: "USB-C, Bluetooth" },
    ],
  },
  {
    id: "camera-mirrorless",
    name: "Камера FramePro X 24Mp",
    brand: "FramePro",
    category: "photo",
    price: 749990,
    rating: 4.9,
    reviews: 198,
    image: "/products/camera.png",
    images: ["/products/camera.png"],
    inStock: false,
    description:
      "Беззеркальная камера для профессионалов с матрицей 24 Мп, быстрым автофокусом и съёмкой видео 4K.",
    specs: [
      { label: "Матрица", value: "24 Мп, полный кадр" },
      { label: "Видео", value: "4K 60 fps" },
      { label: "Автофокус", value: "759 точек" },
      { label: "Стабилизация", value: "5-осевая" },
    ],
  },
  {
    id: "speaker-portable",
    name: "Колонка BoomBox Go",
    brand: "BoomBox",
    category: "audio",
    price: 64990,
    oldPrice: 79990,
    rating: 4.4,
    reviews: 756,
    image: "/products/speaker.png",
    images: ["/products/speaker.png"],
    badge: "sale",
    inStock: true,
    description:
      "Портативная влагозащищённая колонка с глубоким басом и автономностью до 24 часов.",
    specs: [
      { label: "Мощность", value: "30 Вт" },
      { label: "Защита", value: "IP67" },
      { label: "Автономность", value: "до 24 часов" },
      { label: "Подключение", value: "Bluetooth 5.3" },
    ],
  },
  {
    id: "laptop-pro-16",
    name: "Ноутбук Aurora Pro 16 M3 Max",
    brand: "Aurora",
    category: "laptops",
    price: 1299990,
    rating: 4.9,
    reviews: 421,
    image: "/products/laptop.png",
    images: ["/products/laptop.png"],
    badge: "new",
    inStock: true,
    description:
      "Профессиональный ноутбук с чипом M3 Max для самых требовательных задач: монтаж, 3D и разработка.",
    specs: [
      { label: "Процессор", value: "Aurora M3 Max, 16 ядер" },
      { label: "Память", value: "48 ГБ" },
      { label: "Накопитель", value: "1 ТБ SSD" },
      { label: "Экран", value: "16\" Liquid Retina XDR" },
      { label: "Автономность", value: "до 22 часов" },
    ],
  },
]

export function formatPrice(value: number) {
  return new Intl.NumberFormat("ru-RU").format(value) + " ₸"
}

export function getProduct(id: string) {
  return products.find((p) => p.id === id)
}

export function getSimilar(product: Product, count = 4) {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, count)
}

export const orders: Order[] = [
  {
    id: "SH-204815",
    date: "12 мая 2026",
    total: 569980,
    status: "shipped",
    items: [
      { product: products[1], qty: 1 },
      { product: products[8], qty: 1 },
    ],
    timeline: [
      { label: "Заказ оформлен", date: "12 мая, 14:20", done: true },
      { label: "Оплата подтверждена", date: "12 мая, 14:22", done: true },
      { label: "Передан в доставку", date: "13 мая, 09:10", done: true },
      { label: "В пути", date: "14 мая, 08:00", done: false },
      { label: "Доставлен", date: "—", done: false },
    ],
  },
  {
    id: "SH-204790",
    date: "28 апреля 2026",
    total: 299990,
    status: "delivered",
    items: [{ product: products[4], qty: 1 }],
    timeline: [
      { label: "Заказ оформлен", date: "28 апр, 11:05", done: true },
      { label: "Оплата подтверждена", date: "28 апр, 11:06", done: true },
      { label: "Передан в доставку", date: "29 апр, 10:00", done: true },
      { label: "В пути", date: "30 апр, 09:30", done: true },
      { label: "Доставлен", date: "1 мая, 15:40", done: true },
    ],
  },
  {
    id: "SH-204612",
    date: "3 апреля 2026",
    total: 159990,
    status: "delivered",
    items: [{ product: products[7], qty: 1 }],
    timeline: [
      { label: "Заказ оформлен", date: "3 апр, 19:12", done: true },
      { label: "Оплата подтверждена", date: "3 апр, 19:13", done: true },
      { label: "Передан в доставку", date: "4 апр, 12:00", done: true },
      { label: "В пути", date: "5 апр, 08:45", done: true },
      { label: "Доставлен", date: "6 апр, 13:20", done: true },
    ],
  },
  {
    id: "SH-204588",
    date: "20 марта 2026",
    total: 49990,
    status: "cancelled",
    items: [{ product: products[8], qty: 1 }],
    timeline: [
      { label: "Заказ оформлен", date: "20 мар, 16:00", done: true },
      { label: "Отменён", date: "20 мар, 18:30", done: true },
    ],
  },
]
