import uuid
from typing import Protocol


class PermissionRepository(Protocol):
    async def get_user_permissions(self, user_id: uuid.UUID) -> frozenset[str]: ...
    async def get_user_roles(self, user_id: uuid.UUID) -> list[str]: ...
    async def assign_role(self, user_id: uuid.UUID, role_name: str) -> None: ...
