import uuid
from typing import Protocol

from app.domain.entity.session_entity import CreateSession, SessionEntity


class SessionRepository(Protocol):
    async def create(self, data: CreateSession) -> SessionEntity: ...
    async def get_by_token_hash(self, token_hash: str) -> SessionEntity | None: ...
    async def revoke(self, session_id: uuid.UUID) -> None: ...
    async def revoke_all_by_user_id(self, user_id: uuid.UUID) -> None: ...
    async def update_last_used(self, session_id: uuid.UUID) -> None: ...
    async def has_active_session(self, user_id: uuid.UUID) -> bool: ...
