import uuid
from typing import Protocol

from app.domain.entity.address_entity import AddressEntity, CreateAddress, UpdateAddress


class AddressRepository(Protocol):
    async def get_all_by_user(self, user_id: uuid.UUID) -> list[AddressEntity]: ...

    async def get_by_id(self, address_id: uuid.UUID) -> AddressEntity | None: ...

    async def create(self, data: CreateAddress) -> AddressEntity: ...

    async def update(self, address_id: uuid.UUID, data: UpdateAddress) -> AddressEntity: ...

    async def delete(self, address_id: uuid.UUID) -> None: ...

    async def unset_default(self, user_id: uuid.UUID) -> None: ...
